// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAofFK0YxSfvuo--nvPATDKw2ib0NuVEkY',
    appId: '1:427740647668:web:9540238f0020fca7070ea1',
    messagingSenderId: '427740647668',
    projectId: 'cabsapp-52a05',
    authDomain: 'cabsapp-52a05.firebaseapp.com',
    storageBucket: 'cabsapp-52a05.firebasestorage.app',
    measurementId: 'G-79G918K8HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5glhTa8Y2pnIKcBulff2Cng9f1XaXwvM',
    appId: '1:427740647668:android:9ae62b1767723a6f070ea1',
    messagingSenderId: '427740647668',
    projectId: 'cabsapp-52a05',
    storageBucket: 'cabsapp-52a05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC87NYEPA1Oia43oLs93wEH-nRSsFz37E',
    appId: '1:427740647668:ios:26bc84b584f3e4db070ea1',
    messagingSenderId: '427740647668',
    projectId: 'cabsapp-52a05',
    storageBucket: 'cabsapp-52a05.firebasestorage.app',
    iosBundleId: 'com.example.cabsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC87NYEPA1Oia43oLs93wEH-nRSsFz37E',
    appId: '1:427740647668:ios:26bc84b584f3e4db070ea1',
    messagingSenderId: '427740647668',
    projectId: 'cabsapp-52a05',
    storageBucket: 'cabsapp-52a05.firebasestorage.app',
    iosBundleId: 'com.example.cabsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAofFK0YxSfvuo--nvPATDKw2ib0NuVEkY',
    appId: '1:427740647668:web:b9889672c257edba070ea1',
    messagingSenderId: '427740647668',
    projectId: 'cabsapp-52a05',
    authDomain: 'cabsapp-52a05.firebaseapp.com',
    storageBucket: 'cabsapp-52a05.firebasestorage.app',
    measurementId: 'G-PH3G66GPXH',
  );
}
